web:
  restart: always
  build: ./web
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  environment:
    DEBUG: 'False'
    SECRET_KEY : 5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
    DB_NAME : postgres
    DB_USER : postgres
    DB_PASS : postgres
    DB_SERVICE : postgres
    DB_PORT : 5432
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx
  volumes_from:
    - web
  links:
    - web:web

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
